---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iot-pipeline-clusterrole 
rules:
  - apiGroups: ['']
    resources: ['pods', 'services', 'endpoints']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iot-pipeline-binding
roleRef:
  kind: ClusterRole
  name: iot-pipeline-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: admin
    apiGroup: rbac.authorization.k8s.io
  # - kind: ServiceAccount
  #   name: pod-inspector
  #   namespace: iot-pipeline