global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@iot-pipeline.local'
  smtp_auth_username: 'alertmanager@iot-pipeline.local'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/alerts'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@iot-pipeline.local'
        from: 'alertmanager@iot-pipeline.local'
        subject: 'CRITICAL: IoT Pipeline Alert'
        html: |
          <h2>Alert: {{ .GroupLabels.alertname }}</h2>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          
          <h3>Details:</h3>
          <ul>
          {{ range .Alerts }}
          <li>Instance: {{ .Labels.instance }}</li>
          <li>Job: {{ .Labels.job }}</li>
          <li>Severity: {{ .Labels.severity }}</li>
          <br>
          {{ end }}
          </ul>

  - name: 'warning-alerts'
    email_configs:
      - to: 'ops@iot-pipeline.local'
        from: 'alertmanager@iot-pipeline.local'
        subject: 'WARNING: IoT Pipeline Alert'
        html: |
          <h2>Alert: {{ .GroupLabels.alertname }}</h2>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']