apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
  namespace: iot-pipeline
spec:
  serviceName: timescaledb
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      # Set security context for the pod: allow group write for mounted volume
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
        
      # Add init container to ensure data directory is properly set up
      initContainers:
      - name: init-db-directory
        image: timescale/timescaledb:latest-pg16
        command:
        - sh
        - -c
        - |
          # Remove lost+found if it exists
          rm -rf /var/lib/postgresql/data/lost+found
          # Create pgdata subdirectory
          mkdir -p /var/lib/postgresql/data/pgdata
          # Set proper ownership
          chown -R 999:999 /var/lib/postgresql/data
          echo "Directory prepared successfully"
        volumeMounts:
        - name: timescaledb-data
          mountPath: /var/lib/postgresql/data

      containers:
      - name: timescaledb
        image: timescale/timescaledb:latest-pg16
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: iot-pipeline-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iot-pipeline-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: iot-pipeline-secrets
              key: POSTGRES_DB
        - name: POSTGRES_INITDB_ARGS
          value: "--encoding=UTF8 --locale=C --auth-host=scram-sha-256"
        - name: TIMESCALEDB_TELEMETRY
          value: "off"
        # PostgreSQL performance tuning for low resources
        - name: POSTGRES_SHARED_BUFFERS
          value: "256MB"
        - name: POSTGRES_WORK_MEM
          value: "16MB"
        - name: POSTGRES_MAINTENANCE_WORK_MEM
          value: "128MB"
        - name: POSTGRES_EFFECTIVE_CACHE_SIZE
          value: "1GB"
        volumeMounts:
        - name: timescaledb-data
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d

        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "800m"

        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - iot_user
            - -d
            - iot_data
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - iot_user
            - -d
            - iot_data
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          
      volumes:
      - name: init-script
        configMap:
          name: timescaledb-init

  # Persistent volume claim templates
  volumeClaimTemplates:
  - metadata:
      name: timescaledb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: premium-rwo
      resources:
        requests:
          storage: 20Gi