apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
provisioner: pd.csi.storage.gke.io # For GCP, change based on cloud provider
parameters:
  type: pd-ssd
  replication-type: none
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-storage
provisioner: pd.csi.storage.gke.io # For GCP, change based on cloud provider
parameters:
  type: pd-standard
  replication-type: none
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer