apiVersion: v1
kind: Service
metadata:
  name: kafka-jmx-exporter
  namespace: iot-pipeline
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - port: 9101
    targetPort: 9101
    name: jmx-metrics
  selector:
    app: kafka